// ====== UI ======
const meLabel = document.getElementById("meLabel");
const userList = document.getElementById("userList");
const chatTitle = document.getElementById("chatTitle");
const chatSubtitle = document.getElementById("chatSubtitle");
const messagesEl = document.getElementById("messages");
const consoleMessagesEl = document.getElementById("consoleMessages");
const textInput = document.getElementById("textInput");
const sendBtn = document.getElementById("sendBtn");
const switchUserBtn = document.getElementById("switchUserBtn");
const adminToggleBtn = document.getElementById("adminToggleBtn");
const adminControls = document.getElementById("adminControls");
const adminA = document.getElementById("adminA");
const adminB = document.getElementById("adminB");
const adminLoadBtn = document.getElementById("adminLoadBtn");
const typingIndicator = document.getElementById("typingIndicator");
